//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMaster
    {
        public int E_ID { get; set; }
        public string StaffName { get; set; }
        public int Age { get; set; }
        public string Position { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}
